name: Push job

on:
  push:
    branches:
      - main

jobs:
  push_to_train_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Verify Token Permissions
        run: |
            curl -H "Authorization: Bearer $GITHUB_TOKEN" -X GET https://api.github.com/repos/swar41/ammoG_Devs
        env:
            GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Push to Train Repository
        run: |
          git remote add train-repo https://github.com/swar41/ammoG_Test.git
          git push train-repo main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT}}
          

