name: Push job

on:
  push:
    branches:
      - main

jobs:
  push_to_train_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
     
      - name: Push to Train Repository
        run: |
          git remote add train-repo https://github.com/swar41/ammoG_Test.git
          git push train-repo main
        env:
          SSH_KEY: ${{ secrets.PUSH_TOKEN}}
          

